[staff] # this could be defined in another file

	[staff.persona]
	unavailable = [
		["2019-01-01", "2019-01-3", "vacation"],
		["2019-02-01", "offsite"],
		["2019-02-27", "2019-02-30"],
    ["2019-3-3"],
	]
  office = "ZRH"

	[staff.personb]
	weekends = ["WED", "fri", "SAT"] # hand lower case
	commitment = 0.7 # should also handle 70%

[office]
ZRH = ["CH", "ZH"]
SVL = ["US", "CA"]

[tasks]

	[tasks.A]
	days = 5
	fat = 2
	staff = "persona"
	title = "prep"
	start = "2019-01-01"

	[tasks.C]
	days = 14
	staff = "personb"

  [tasks.B]
  start = "2019-1-3"

[requires]
C = ["A", "B"]
#C = "A"
